resources:

  # Expose les entités de type Book
  App\Entity\Book:

    shortName: 'book'
    description: 'Représente un livre attaché à 0 ou 1 Author et à 0 à n Tags.'

    attributes:
      # Défini la sécurité globale sur cette entité (sauf mention contraire seuls les admins pourront lire, créer, modifier, supprimer ce type de ressources)
      security: 'is_granted("ROLE_ADMIN")'
      # Préfixe toutes les routes de cette entité avec media
      route_prefix: /media
      # Paramètrage du contenu renvoyé (utilisation du contexte show_book pour sérialiser, les champs ayant une valeur nulle sont quand meme affichés).
      normalization_context:
        groups: ['show_book']
        skip_null_values: false
      # Définition de la pagination et de l'ordre par défaut.
      pagination_items_per_page: 10
      order:
        title: asc

    # Enumération et configuration des opérations autorisées
    collectionOperations:
      # Autorise uniquement les utilisateurs authentifiés à lister / rechercher des livres et défini les possibilités de filtrage et de tri
      get:
        security: 'is_granted("ROLE_USER")'
        filters: ['book.search_filter', 'book.order_filter']
      # Active la création de nouveau livre (la méthode n'est pas activée par défaut)
      post: ~

    # Autorise la lecture d'un livre par tout le monde, mais la modification uniquement par un admin ! (non utilisé pour le client actuellemnt)
    itemOperations:
      get:
        security: 'is_granted("IS_AUTHENTICATED_ANONYMOUSLY")'
      # Active explicitement la modification ou la suppression d'un livre existant
      put: ~
      delete: ~
      

