resources:

  App\Entity\Book:
    shortName: 'book'
    description: 'Livre existant en base de données.'
    attributes:
      pagination_items_per_page: 10
      order:
        title: asc
    collectionOperations:
      get:
        filters: ['book.search_filter', 'book.order_filter']


