lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'     # La clef privée
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'     # La clef publique
    pass_phrase: '%env(JWT_PASSPHRASE)%'            # Le mot de passe permettant de décrypter les clefs
    token_ttl: 3600